name: Function App - Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/batch/**'
permissions:
  contents: read

jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest
    env:
      APP_NAME: "backend-app"
      DOCKERFILE: "docker/Backend.Dockerfile"
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
          
        - name: Docker Login
     
          uses: docker/login-action@v3
          with:
            registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
            username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USER_NAME}}
            password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
    
        - name: Get current date
          id: date
          run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    
        - name: Build Docker Image and optionally push
          uses: docker/build-push-action@v6
          with:
            context: .
            file: ${{ inputs.dockerfile }}
            push: ${{ inputs.push }}
            cache-from: type=registry,ref=${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ inputs.app_name}}:latest
            tags: |
              ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ inputs.app_name}}:latest
              ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ inputs.app_name}}:${{ steps.date.outputs.date }}_${{ github.run_number }}
