name: Backend App - Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/batch/**'
permissions:
  contents: read
  id-token: write
env:
    APP_NAME: "backend-app"
    DOCKERFILE: "docker/Backend.Dockerfile"

jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Docker Login

          uses: docker/login-action@v3
          with:
            registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
            username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USER_NAME}}
            password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Get current date
          id: date
          run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

        - name: Set Docker tags
          id: docker-tags
          run: |
            echo "LATEST_TAG=${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ env.APP_NAME }}:latest" >> $GITHUB_ENV
            echo "VERSION_TAG=${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ env.APP_NAME }}:${{ github.run_number }}" >> $GITHUB_ENV
            echo "::set-output name=custom-image-name::${{ env.APP_NAME }}:${{ github.run_number }}"

        - name: Build Docker Image and optionally push
          uses: docker/build-push-action@v6
          with:
            context: .
            file: ${{ env.DOCKERFILE }}
            push: true
            cache-from: type=registry,ref=${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ env.APP_NAME}}:latest
            tags: |
             ${{ env.LATEST_TAG }}
             ${{ env.VERSION_TAG }}

  deploy-backend-app:
      needs: build-push-docker-image
      runs-on: ubuntu-latest
      environment:
        name: 'dev'

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Azure Login
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Set Azure Function App settings
          run: |
            az functionapp config container set \
              --name ${{ secrets.AZURE_FUNCTION_APP_NAME }} \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --docker-custom-image-name  ${{ env.APP_NAME }}:${{ github.run_number }} \
              --docker-registry-server-url https://${{ secrets.AZURE_CONTAINER_REGISTRY }} \
              --docker-registry-server-user ${{ secrets.AZURE_CONTAINER_REGISTRY_USER_NAME }} \
              --docker-registry-server-password ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
