name: Backend App - Build and Deploy Docker Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/batch/**'
permissions:
  contents: read
  id-token: write


jobs:
  build-push-docker-image:
   uses: ./.github/workflows/teams-accelerator-build-push-docker.yml
   with:
      app_name: ${{ env.APP_NAME }}
      dockerfile: ${{ env.DOCKERFILE }}
      push: true
   secrets:
      inherit
   env:
    APP_NAME: "backend-app"
    DOCKERFILE: "docker/Backend.Dockerfile"


  deploy-backend-app:
      needs: build-push-docker-image
      runs-on: ubuntu-latest
      environment:
        name: ${{ github.ref != 'refs/heads/main' && 'dev' || 'prod' }}

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Azure Login
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Set Azure Function App settings
          run: |
            az functionapp config container set \
              --name ${{ secrets.AZURE_FUNCTION_APP_NAME }} \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --docker-custom-image-name  ${{ env.APP_NAME }}:${{ github.run_number }} \
              --docker-registry-server-url https://${{ secrets.AZURE_CONTAINER_REGISTRY }} \
              --docker-registry-server-user ${{ secrets.AZURE_CONTAINER_REGISTRY_USER_NAME }} \
              --docker-registry-server-password ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
