name: Function App - Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/batch/**'
permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    env:
      APP_NAME: "backend-app"
      DOCKERFILE: "docker/Backend.Dockerfile"
    steps:
        - name: Build and Push Docker Image
          uses: ./.github/workflows/teams-accelerator-build-push-docker.yml
          with:
            registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
            username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USER_NAME}}
            password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
            app_name: ${{ env.APP_NAME }}
            dockerfile: ${{ env.DOCKERFILE }}
          #push: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_branch == 'main' }}
       
