name: Admin - Frontend App - Build and Deploy Docker Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'code/backend/Admin.py'
      - 'code/backend/pages/**'
permissions:
  contents: read
  id-token: write

jobs:
  build-push-docker-image:
   uses: ./.github/workflows/reusable-build-push-docker-image.yml
   with:
      dockerfile: "docker/Admin.Dockerfile"
      image_name: "admin-frontend-app"
   secrets:
      inherit

  deploy-backend-app:
      needs: build-push-docker-image
      uses: ./.github/workflows/reusable-deploy-docker-image.yml
      with:
        image_name: "admin-frontend-app"
        deploy_command: "app-service"
      secrets:
        inherit
