name: Frontend App - Build and Deploy Docker Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'code/frontend/src/**'
permissions:
  contents: read
  id-token: write

jobs:
  build-push-docker-image:
   uses: ./.github/workflows/reusable-build-push-docker-image.yml
   with:
     dockerfile: "docker/Frontend.Dockerfile"
     image_name: ${{ vars.AZURE_APP_SERVICE_IMAGE_NAME }}
   secrets:
     inherit

  deploy-app:
    needs: build-push-docker-image
    uses: ./.github/workflows/reusable-deploy-docker-image.yml
    with:
      image_name: ${{ vars.AZURE_APP_SERVICE_IMAGE_NAME }}
      deploy_command: "app-service"
      service_name: ${{ vars.AZURE_APP_SERVICE_NAME }}
    secrets:
      inherit
