name: Frontend App - Build and Deploy Docker Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'frontend/src/**'
permissions:
  contents: read
  id-token: write

env:
  APP_NAME: "frontend-app"

jobs:
  build-push-docker-image:
   uses: ./.github/workflows/reusable-build-push-docker.yml
   with:
      app_name: "frontend-app"
      dockerfile: "docker/Frontend.Dockerfile"
      push: true
   secrets:
      inherit

  deploy-backend-app:
      needs: build-push-docker-image
      runs-on: ubuntu-latest
      environment:
        name: ${{ github.ref != 'refs/heads/main' && 'dev' || 'prod' }}

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Azure Login
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Set Azure App Service container settings
          run: |
            az webapp config container set \
              --name ${{ secrets.AZURE_APP_SERVICE_NAME }} \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --docker-custom-image-name  ${{ env.APP_NAME }}:${{ github.run_number }} \
              --docker-registry-server-url https://${{ secrets.AZURE_CONTAINER_REGISTRY }} \
              --docker-registry-server-user ${{ secrets.AZURE_CONTAINER_REGISTRY_USER_NAME }} \
              --docker-registry-server-password ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
