name: Admin - Frontend App - Build and Deploy Docker Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'code/backend/Admin.py'
      - 'code/backend/pages/**'
permissions:
  contents: read
  id-token: write

jobs:
  build-push-docker-image:
   uses: ./.github/workflows/reusable-build-push-docker-image.yml
   with:
      dockerfile: "docker/Admin.Dockerfile"
      image_name: "admin-frontend-app"
   secrets:
      inherit

  deploy-backend-app:
      needs: build-push-docker-image
      runs-on: ubuntu-latest
      environment:
        name: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
      env:
        IMAGE_NAME: ${{ needs.build-push-docker-image.outputs.container_image }}


      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Print environment variables
          run: |
            echo "Using IMAGE_NAME: ${{ env.IMAGE_NAME }}"

        - name: Azure Login
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Set Admin Azure App Service container settings
          run: |
            az webapp config container set \
              --name ${{ secrets.AZURE_ADMIN_APP_SERVICE_NAME }} \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --container-image-name   ${{ env.IMAGE_NAME}} \
              --container-registry-url https://${{ secrets.AZURE_CONTAINER_REGISTRY }} \
              --container-registry-user ${{ secrets.AZURE_CONTAINER_REGISTRY_USER_NAME }} \
              --container-registry-password ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
