name: Deploy and Register Teams App (Bicep Template)

on:
    workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy-teams-app:
    environment:
      name: 'prod'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1

      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy Bicep template
      run: |
        az deployment group create \
          --resource-group rg-teamsaccelerator-1 --template-file extensions/teams/infra/azure.bicep \
          --parameters resourceBaseName='codewith-TeamsApp' botAadAppClientId='869b89bd-30a2-4376-a248-ed64443bd0b5' botAadAppClientSecret='test' azureFunctionURL='testfuncurl' webAppSKU='S1' botDisplayName='test-pm-bot'
