name: Reusable Docker build and push workflow

on:
  workflow_call:


   inputs:
      app_name:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      push:
        required: true
        type: boolean

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login

        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USER_NAME}}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Docker tags
        id: docker-tags
        run: |
          echo "LATEST_TAG=${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ inputs.app_name }}:latest" >> $GITHUB_ENV
          echo "VERSION_TAG=${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ inputs.app_name }}:${{ github.run_number }}" >> $GITHUB_ENV


      - name: Build Docker Image and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          cache-from: type=registry,ref=${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ inputs.app_name}}:latest
          tags: |
            ${{ env.LATEST_TAG }}
            ${{ env.VERSION_TAG }}
