name: Reusable Docker build and push workflow

on:
  workflow_call:
   inputs:
      dockerfile:
        required: true
        type: string

jobs:
  docker-build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    env:
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
      LATEST_TAG: ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ vars.IMAGE_NAME }}:latest
      VERSION_TAG: ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ github.run_number }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USER_NAME}}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          cache-from: type=registry,ref=${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ vars.image_name}}:latest
          tags: |
            ${{ env.LATEST_TAG }}
            ${{ env.VERSION_TAG }}
