name: Reusable Docker build and push workflow

on:
  workflow_call:
   inputs:

      image_name:
          required: true
          type: string

      source_environment:
        required: true
        type: string

      destination_environment:
        required: true
        type: string

jobs:
  get-source-acr-details:
    runs-on: ubuntu-latest
    environment: ${{ inputs.source_environment }}
    # outputs:
    #   source_acr: ${{ steps.get-source-acr-credentials.outputs.source_acr }}
    #   source_acr_user_name: ${{ steps.get-source-acr-credentials.outputs.source_acr_un }}
    #   source_acr_password: ${{ steps.get-source-acr-credentials.outputs.source_acr_pwd }}
    steps:

      - name: Get Source ACR credentials
        id: get-source-acr-credentials
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |

            az_source_acr=${{  secrets.AZURE_CONTAINER_REGISTRY }}

            echo "source_acr=$az_source_acr" >> $GITHUB_ENV

            az_source_acr_un=${{ secrets.AZURE_CONTAINER_REGISTRY_USER_NAME }}

            echo "source_acr_un=$az_source_acr_un" >> $GITHUB_ENV

            az_source_acr_pwd=${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

            echo "source_acr_pwd=$az_source_acr_pwd" >> $GITHUB_ENV


  get-dest-acr-details:
      runs-on: ubuntu-latest
      environment: ${{ inputs.destination_environment }}
      outputs:
        dest-acr: ${{ steps.get-dest-acr-credentials.outputs.dest-acr }}
        dest-acr-user-name: ${{ steps.get-dest-acr-credentials.outputs.dest-acr-un }}
        dest-acr-password: ${{ steps.get-dest-acr-credentials.outputs.dest-acr-password }}
      steps:
        - name: Get Destination ACR credentials
          id: get-dest-acr-credentials
          uses: azure/cli@v2
          with:
            azcliversion: latest
            inlineScript: |
              az_dest_acr=${{ secrets.AZURE_CONTAINER_REGISTRY }}
              echo "::set-output name=dest-acr::$az_dest_acr"

              az_dest_acr_un=${{ secrets.AZURE_CONTAINER_REGISTRY_USER_NAME }}
              echo "::set-output name=dest-acr-un::$az_dest_acr_un"

              az_dest_acr_pwd=${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
              echo "::set-output name=dest-acr-password::$az_dest_acr_pwd"

  docker-copy-image:
    runs-on: ubuntu-latest
    needs: [get-source-acr-details, get-dest-acr-details]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login to source ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.source_acr }}
          username: ${{ env.source_acr_un }}
          password: ${{ env.source_acr_pwd  }}

      - name: Pull Docker image from Source ACR
        run: |
           docker pull ${{ needs.get-source-acr-details.outputs.source-acr }}/${{ inputs.image_name }}:latest

      - name: Tag Docker image for Destination ACR
        run: |
          docker tag ${{ needs.get-source-acr-details.outputs.source-acr }}/${{ inputs.image_name }}:latest ${{ needs.get-dest-acr-details.outputs.dest-acr }}/${{ inputs.image_name }}:latest

      - name: Docker Login to destination ACR
        uses: docker/login-action@v3
        with:
            registry: ${{ needs.get-dest-acr-details.outputs.dest-acr }}
            username: ${{ needs.get-dest-acr-details.outputs.dest-acr-user-name }}
            password: ${{ needs.get-dest-acr-details.outputs.dest-acr-password }}

      - name: Push Docker image to Destination ACR
        run: |
          docker push ${{ needs.get-dest-acr-details.outputs.dest-acr }}/${{ inputs.image_name }}:latest
