name: Reusable Docker build and push workflow

on:
  workflow_call:
   secrets: inherit
    inputs:
      app_name:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      push:
        required: true
        type: boolean
        default: true
     

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker Login
      if: ${{ inputs.push }}
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USER_NAME}}
        password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Build Docker Image and optionally push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        cache-from: type=registry,ref=${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ inputs.app_name}}:latest
        tags: |
          ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ inputs.app_name}}:latest
          ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ inputs.app_name}}:${{ steps.date.outputs.date }}_${{ github.run_number }}
